### Register Account
POST http://localhost:3000/api/v1/auth/register

{
    "name" : "dynacode",
    "email": "dynacode@gmail.com",
    "password": "dynacode",
    "phone_number": "0876796969"
}

### Login Account
POST http://localhost:3000/api/v1/auth/login

{
    "email": "testing1@gmail.com",
    "password": "testing"
}